checksumBehavior: update

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${NPM_AUTH_TOKEN-fallback}"

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org/"

npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"

ignorePath: false
yarnPath: .yarn/releases/yarn-4.9.2.cjs